### ISSUE TITLE
Reversed WAR temperatures

### ISSUE THREAD

**Issue by root2k** [edterbak/NodeRed_Heishamon_control#64] opened 2023-01-16 06:21 UTC
The temperatures of the WAR for high and low temperature is reversed.
My heat curve is 30 at -15 an 25 at 13 degrees. But if I look into WAR it shows me 30 at 13 an 25 at -15 degrees.
Consequently the graph is also wrong.

![grafik](https://user-images.githubusercontent.com/116718093/212611045-08fe5364-6123-40af-a1f3-634c56162ae2.png)

2nd problem is, if I switch the button WAR on it turns back into off after 3 secounds.
Maybe it isn't a bug but I don't know.

3rd thing, I don't see anything at "calculated temp" in WAR menu.

**Comment by edterbak** [comment] 2023-01-16 18:58
Hi root2k,

what version of flow are you using. 21.00 stable? or a beta version.

**Comment by root2k** [comment] 2023-01-16 19:42
I have copied the content of the flows.json (flow date 2 months ago). I guess thats the stable version 21.00?
My Heisha heat mode is compensation curve and the outdoor temperature offset ist at 13 degrees.

What should I have to change, so that is working as it should?

**Comment by edterbak** [comment] 2023-01-17 21:54
There is a newer version. try from this page.
it has a lot lot lot of fixes. 
among one, the WAR issue you mention.

https://github.com/edterbak/NodeRed_Heishamon_control/tree/main-22-beta_2

**Comment by root2k** [comment] 2023-01-18 08:58
I have tried it, in this version the WP_MQTT flow is missing, but isn'5t really nessesary because it was just an overvie of the topics, right?

In this version the WAR temperatures are displayed correct.
But teh other thing I have recognized is, that there is no possibility to change the outlet setpoint.
On home screen there is just the actual outlet setpoint written but no possibility to adjust this like in the DHW part with arrows for up and down?

But it is still the same, I can't activate the nodered WAR as long as the pana is in compensation curve mode.
Need to be set to direct mode otherwise the nodered WAR function will be diasbled after 3 sec.

When will be this flow a stable version?

**Comment by root2k** [comment] 2023-01-20 06:49
I explain it with more details ...
I don't set my pana into direct mode on the remote controller before using this nodered flow.
That's why I'm thinking it don't work well so far.
I thought that is not nessesary anymore, because edterbak has written in the changelog.
So this might be the issue why the WAR switch is turned off 3 sec. after activating.

To the outlet setpoint correction, yes a manual correction would be nice (picture red marked). Like the DHW setpoint (picture marked green).
![grafik](https://user-images.githubusercontent.com/116718093/213634736-cbeab920-ae78-4958-9b5a-8a572a6ef165.png)


And the last thing is, I don't know if this is a bug or just the result why the WAR function isn't activated, I don't see any calculated setpoint temperature ...
![grafik](https://user-images.githubusercontent.com/116718093/213634592-96ba6c44-91a2-4248-93f4-67723172170c.png)

**Comment by edterbak** [comment] 2023-01-23 23:28
Hi root2k,

What you ask for is contradictory to my feeling. And if I actually am understanding correctly, impossible.

If you have your heatpump setup to use the compensation curve (this is indeed now possible), then:
1 - you cannot talk about a setPOINT. a setpoint is one defined point, not dependant on anything else. 
2 - the water temperature is controlled by the panasonic. 100%.*
3 - because of point 1+2, it is of no use to offer a button to increase/decrease a target temperature. 
4 - it is only able to use the panasonic outside temperature sensor. Only the sensor directly connected how pana expects it. So no homebrew sensor through Node Red. 

*2 -  only exception is the RTC function as Maarten mentions. It can shift the entire curve (in the panasonic) by -5/+5 degrees depending on the room temperature.  

When using compensation curve, is of no use to activate the WAR function inside node red, I force it off after checking the heating mode. 

The last point you made, yes, that might be a bug :) thanks for letting know. I will have a look at this later. 

I hope I understand you correct, and what I write is a good answer to your question.

regards,

**Comment by root2k** [comment] 2023-01-24 05:51
Hi edterbak,

thanks for your response.
I may think we are not talking about the same thing in some points.
What  I mean with the correction of the setpoint is the same thing you can do at the remote conrol of the panasonic.
There you can change the setpoint from -5 to +5.
That is, at the moment, an important tool for me because I'm struggeling since 3 years with a problem after dhw of the panasonic.
Let me explain, the compresor falls back to 0 hz after heating up the water tank. What I know is that it's sometimes a pana control problem. To wake up the pana for heating I'm doing a setpoint correction up to +3 on the remote control or the cloud modul, manually. That works for me and the pana is starting heating again. But If I use this flow, I can't do this any more.
Therefore I have to create a flow or something that the pana is doing this on her own, but don't know if this works together with your flow?

And to your last point activating the WAR mode is not nessesary, nice to know.
So that's normal behavior when using the WAR function, that nodered switches the WAR button auotmatically off, do I understand right?

Big thanks to your effort.

regards.

**Comment by edterbak** [comment] 2023-01-25 01:46
root2k,

Ah, I understand now. 
(Technically we call changing the setpoint you mean: 'shifting' the compensation curve up or down. But thats besides the point.)

I got thrown off a bit when the story went from a problem to problem solved (in newer version) whereafter it slided to new feature request. That last part was unclear. 


Could you please make an issue with a new feature request for this?
To be clear. You write about two feature requests.
1 - the option to use the setpoint arrows on the dashboard to shift when in compensation curve mode. 
2 - the function to automatically shift +3 for 30 seconds, after DHW cycle finished. 

item 1 is a good one. Logical and easy to make I would say. 

There might already be a request for item 2, but for item 1 I know there is none. Crazy when I think about it...

Many thanks. :)

**Comment by edterbak** [comment] 2023-01-25 02:02
Design wise, I am thinking of the following solution with the motivation below. Kindly your thoughts. 
<img src="https://github.com/edterbak/NodeRed_Heishamon_control/blob/main/images/2023-01-25%2002_49_28-Node-RED%20Dashboard.png?raw=true" width="1000">

The CURRENT dashboard is build up like this:
1 - You insert the target water temperature. If no other function below is active to override/correct (2 - 5) then that would endup below as final water setpoint at 6. 
After it is sent to the heatpump and confirmed, it shows in the dashboard on the left section at 7.

Proposal for the new situation adapting for SHIFT:
1 - Depending on the Operating Mode (Direct or Compensation Curve) change the text of 1
Use the same up/down toggles in the same location for shifting the curve
2 - automatically disabled.
3-5 can still be used together with shifting
6 the final corrected shift will be shown here.

After it has been sent and confirmed the shift will be shown at 7

The labels on item 1, 6 and 7 should be made dynamic based on Direct/Compensation curve.

**Comment by root2k** [comment] 2023-01-25 05:54
Hi edterbak,

thank you for your reply.
Yeah I don't even know the right technically word, thanks for telling me. But it's excactly what I mean, shifting up and down of the compensation curve by using the setpoint correction.

I will make two feature requests when I'm done writing this message.

To your thoughts of the implementation of the shifting part: I think that would be nice if it works like you have written above.
But I thought, as you have written before, the disabling of the WAR function is automatically done right now when the user don't set the heatpump into direct mode?

So the WAR function will be disabled after shifting up or down of the compensation curve. But in case of the shifting correction, it would be cool to automatically set it back to 0 when the user enables the WAR function again. Do you have the same thoughts about this?

**Comment by edterbak** [comment] 2023-01-25 06:58
:) Hi again.

Thanks for the requests!
I will respond in the respective issues. Thanks again.

**Comment by edterbak** [comment] 2023-01-26 21:33
Fixed in 22.00

**Closed** 2023-01-26 21:33 UTC
Labels: bug
