### ISSUE TITLE
[BUG]: WAR loses values

### ISSUE THREAD

**Issue by mabek** [edterbak/NodeRed_Heishamon_control#151] opened 2024-01-06 19:07 UTC
Recently on 24.02 my WAR loses the values but seems to continue working, see screenshot.
<img width="1078" alt="Bildschirmfoto 2024-01-06 um 20 04 06" src="https://github.com/edterbak/NodeRed_Heishamon_control/assets/7482652/85c08b95-75c3-4d93-8a26-be322e52de65">

Recent Log:
06/01 20:05:42 - MQTT Command: SetCurves: target: 24 (SP Calculation)
06/01 20:05:42 - Function - Calculate new SP: New final SP calculated: Current setpoint: 25 °C. New calculated setpoint: 24 °C
06/01 20:05:42 - Function NightReduction: 1
06/01 20:05:42 - Scheduler - NightReduction water temp: -1
06/01 20:05:41 - Function - SoftStart: 0
06/01 20:05:41 - Scheduler: Turn OFF function: SoftStart
06/01 20:02:58 - Function WAR: Setpoint change: From 24.7 to 24.9 °C
06/01 19:52:48 - Function WAR: Setpoint change: From 24.9 to 24.7 °C
06/01 19:47:48 - Function WAR: Setpoint change: From 24.7 to 24.9 °C
06/01 19:45:58 - Function WAR: Setpoint change: From 24.9 to 24.7 °C
06/01 19:42:38 - Function WAR: Setpoint change: From 24.7 to 24.9 °C
06/01 19:37:38 - Function WAR: Setpoint change: From 24.9 to 24.7 °C
06/01 19:32:38 - Function WAR: Setpoint change: From 24.7 to 24.9 °C
06/01 19:27:38 - Function WAR: Setpoint change: From 24.9 to 24.7 °C
06/01 19:14:37 - Function WAR: Setpoint change: From 25 to 24.9 °C
06/01 19:12:07 - Function SoftStart: SoftStart function end
06/01 19:12:07 - Compressor: stopped
06/01 18:52:27 - Function WAR: Setpoint change: From 24.9 to 25 °C
06/01 18:44:37 - Function WAR: Setpoint change: From 25 to 24.9 °C
06/01 16:56:26 - Function WAR: Setpoint change: From 24.9 to 25 °C
06/01 16:46:26 - Function WAR: Setpoint change: From 25 to 24.9 °C
06/01 16:44:05 - Function WAR: Setpoint change: From 24.9 to 25 °C
06/01 16:41:25 - SYSTEM - HEISHAMON Connection: Online
06/01 16:41:20 - SYSTEM - HEISHAMON Connection: Offline
06/01 15:54:15 - Function - WAR: 1
06/01 15:15:32 - Function WAR: Setpoint change: From 24.7 to 24.9 °C
06/01 14:45:52 - Function SoftStart: Phase 3 - Phase out step
06/01 14:34:02 - MQTT Command: SetCurves: target: 25 (SP Calculation)
06/01 14:34:02 - Function - Calculate new SP: New final SP calculated: Current setpoint: 26 °C. New calculated setpoint: 25 °C
06/01 14:33:52 - Function SoftStart: Correction: 1 > 0 °C - (ENDING) Freq: 33Hz, SP_Final: 23°C
06/01 14:33:52 - Function SoftStart: Phase 3 - Phase out step
06/01 14:08:12 - Function WAR: Setpoint change: From 24.5 to 24.7 °C
06/01 14:04:52 - Function SoftStart: Start Phase 2
06/01 14:04:36 - MQTT Command: SetCurves: target: 26 (SP Calculation)
06/01 14:04:36 - Function - Calculate new SP: New final SP calculated: Current setpoint: 25 °C. New calculated setpoint: 26 °C
06/01 14:04:36 - Function SoftStart: Correction: 0 > 1 °C - (STARTUP) Freq: 34Hz, SP_Final: 24°C
06/01 14:04:25 - MQTT Command: SetCurves: target: 25 (SP Calculation)
06/01 14:04:25 - Function - Calculate new SP: New final SP calculated: Current setpoint: 24 °C. New calculated setpoint: 25 °C
06/01 14:04:25 - Function SoftStart: Correction: -1 > 0 °C - (STARTUP) Freq: 33Hz, SP_Final: 23°C
06/01 14:04:21 - SYSTEM - HEISHAMON Connection: Online
06/01 14:04:20 - SYSTEM - HEISHAMON Connection: Offline
06/01 14:04:15 - MQTT Command: SetCurves: target: 24 (SP Calculation)
06/01 14:04:15 - Function - Calculate new SP: New final SP calculated: Current setpoint: 23 °C. New calculated setpoint: 24 °C
06/01 14:04:15 - Function SoftStart: Correction: -2 > -1 °C - (STARTUP) Freq: 33Hz, SP_Final: 22°C
06/01 14:03:51 - MQTT Command: SetCurves: target: 23 (SP Calculation)
06/01 14:03:51 - Function - Calculate new SP: New final SP calculated: Current setpoint: 28 °C. New calculated setpoint: 23 °C
06/01 14:03:51 - Function SoftStart: Correction: 0 > -2 °C - (STARTUP) Freq: 21Hz, SP_Final: 21°C
06/01 14:03:51 - Compressor: running
06/01 14:02:41 - Function WAR: Setpoint change: From 24.7 to 24.5 °C
06/01 14:00:51 - Compressor: stopped
06/01 14:00:51 - MQTT Command: SetOperationMode: 0
06/01 14:00:51 - TOP20_ThreeWay_Valve_State: 0
06/01 14:00:51 - TOP4_Operating_Mode_State: 0
06/01 14:00:42 - MQTT Command: SetOperationMode: 0 (scheduler)
06/01 13:00:50 - Function SoftStart: SoftStart function end
06/01 13:00:50 - MQTT Command: SetOperationMode: 4
06/01 13:00:50 - TOP20_ThreeWay_Valve_State: 1
06/01 13:00:50 - TOP4_Operating_Mode_State: 4
06/01 13:00:42 - MQTT Command: SetOperationMode: 4 (scheduler)
06/01 11:54:23 - Function - RTC: 0
06/01 11:54:24 - SYSTEM - HEISHAMON Connection: Online
06/01 11:54:20 - SYSTEM: MQTT Broker: Node Red MQTT node connected
06/01 11:54:17 - Function - SoftStart: 1
06/01 11:54:17 - SYSTEM: Persistent storage: OK
06/01 11:54:16 - SYSTEM: MQTT block inactive, default block mode: UNRESTRICTED
06/01 11:54:16 - SYSTEM: MQTT block inactive, default block mode: UNRESTRICTED
06/01 11:54:16 - Function - Calculate new SP: New final SP calculated: Current setpoint: 28 °C. New calculated setpoint: 25 °C
06/01 11:54:16 - Compressor: running
06/01 11:54:16 - Function WAR: Setpoint change: From 23 to 24.7 °C
06/01 11:54:16 - Function NightReduction: New correction: -1 °C
06/01 11:54:16 - Function - Solar: 0
06/01 11:54:16 - SYSTEM: WAR settings OK
06/01 11:54:16 - SETUP - Sensors: Custom room temperature sensor not found. Using internal sensor (TOP33)
06/01 11:54:16 - SYSTEM: Heatpump zone 2 is set to controle water temperature
06/01 11:54:16 - SYSTEM: Heatpump zone 1 is controlled by thermostat (internal)
06/01 11:54:16 - SYSTEM: Heatpump is in DIRECT mode
06/01 11:54:16 - Function NightReduction: 0
06/01 11:54:16 - TOP20_ThreeWay_Valve_State: 0
06/01 11:54:16 - TOP2_Force_DHW_State: 0
06/01 11:54:16 - SYSTEM - HEISHAMON Connection: Offline
06/01 11:54:16 - SYSTEM: Start---------------------------------------------------------------

================refresh for actual values======================
NightReductionRoomSetpoint.NORMAL: 22
NightReductionRoomSetpoint.LOW: 18
NightReduction room_setpoint.state: 0
---------------------------------------------------------------------------------------------------
F_NR_correction: 0
NightReductionWaterTemp.current_value: 0
NightReductionWaterTemp.correction: -1
NightReductionWaterTemp.state: undefined
---------------------------------------------------------------------------------------------------
F_ReducePumpSpeed.state: 0
F_ReducePumpSpeed.LowSpeed: 205
F_ReducePumpSpeed.NormalSpeed: undefined
F_ReducePumpSpeed.PumpMaxFlowSetting: 254
---------------------------------------------------------------------------------------------------
MQTT.block_mode_previous: UNRESTRICTED
MQTT.block_mode: UNRESTRICTED
MQTT.message_limit: 1900
MQTT.counter: 29406 (total)
MQTT.messages_yesterday: 8
MQTT.messages_today: 12
MQTT.allow_scheduler: 1
MQTT.allow_solar: 0
MQTT.allow_rtc_onoff: 0
MQTT.block_active: 0
---------------------------------------------------------------------------------------------------
Function - SoftStart Quietmode is disabled
---------------------------------------------------------------------------------------------------
Actual runtime: 0 minutes, last runtime: 308 minutes
F_SS.lowerlimit_correction: -1°C (Max. setpoint decrease)
F_SS.upperlimit_correction: 1°C (Max. setpoint increase)
F_SS.total_duration: 30 minutes (Max. time the SoftStart will be active)
Function - SoftStart is disabled
---------------------------------------------------------------------------------------------------
The compressor has started 5 times in the last 24 hours
Highest compressor frequency ever recorded: 59 Hz
Total hours: 2776, starts: 2260, average runtime: 1.23 hours
Total Defrosts: 116, today 0, yesterday 0
Total MQTT-Commands send: 29406, today 12, yesterday 8
---------------------------------------------------------------------------------------------------
RTC Room setpoint 22°C
F_RTC.z1.incremental_setpoints_state: undefined
F_RTC.automation_OM_state: 0 (RTC allow change OM is disabled)
F_RTC.automation_power_state: 0 (RTC turn heat on/off is disabled)
F_RTC.z1.state: 0 (Function RTC is disabled)
F_RTC.automation_active: 0
---------------------------------------------------------------------------------------------------
Schedule_1 ss on, Select,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday, 09:40toggle item (override)
Schedule_2 on, Select,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday, 09:40NightReductionWaterTempOff (override)
Schedule_3 dhw, Select,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday, 13:00, OperationMode4 (override)
Schedule_5 heat, Select,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday, 14:00, OperationMode0 (override)
Schedule_6 night reduc, Select,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday, 20:05, NightReductionWaterTempOn
Schedule_8 soft start off, Select,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday, 20:05, toggle item
Scheduler: 6 tasks are currently active
F_stored_next_operating_mode: undefined (ok)
F_SOLAR.function_active_state: undefined
solar_block_scheduler: undefined (ok)
---------------------------------------------------------------------------------------------------
Found 4 1-wire sensors connected to Heishamon
Found 1 custom kWh-device(s) connected to Heishamon
Total errors: 0, last error: No error
This flow is running for 8 hours without a restart.
SYSTEM Heatpump is in DIRECT mode
Target=24°C, Inlet=23.5°C, Outlet=23.5°C, Freq=0 Hz, Quiet mode=0, 0 Watt
HP power is on, operation mode Heat only, threeway valve in position Room
============================================================

**Comment by edterbak** [comment] 2024-01-07 21:37
Hi!
Ah.. Thank you for posting this bug.
Because the WAR function keeps working, I did not notice it myself. but I can confirm the bug, as I see this myself as well. 

I will figure it out why/where it is coming from.

**Comment by edterbak** [comment] 2024-01-07 21:38
And fix it of course...

**Comment by edterbak** [comment] 2024-01-07 21:52
Next release will contain the fix. will be v23.03 of course

**Comment by edterbak** [comment] 2024-01-14 11:06
v24.03 released, it should be fixed now.

I am closing the issue. I assume it is fixed. I had the issue, fixed it on my end, so it should also be the same for you.

If not, and the problem has not been resolved.... please reopen this issue. :)

**Closed by edterbak** 2024-01-14 11:06 UTC
Labels: bug
